syntax = "proto3";

import "shared.proto";
import "nanopb.proto";

// GO
option go_package = "git-ima.europe.phoenixcontact.com/abacusgo/linkbusgo";

// JAVA settings
option java_multiple_files = false;
option java_package = "com.phoenixcontact.emalyticscatanio.message";
option java_outer_classname = "EmalyticsCatanIoDali";


/* DALI **********************************************************************/
// read, write, disable, power control, gears

enum DaliPktType {
    DALI_LEN_16 = 0;
    DALI_LEN_24 = 1;
    DALI_LEN_25 = 2;
    DALI_LEN_20 = 3;
    DALI_LEN_32 = 4;
    DALI_NO_FF = 5;
}

enum DaliPrio {
    DALI_PRIO_2 = 0;
    DALI_PRIO_3 = 1;
    DALI_PRIO_4 = 2;
    DALI_PRIO_5 = 3;
}

enum DaliAnswerType {
    DALI_ANSWER_NO = 0;
    DALI_ANSWER_VALID = 1;
    DALI_ANSWER_INVALID = 2;
}

enum DaliPktOrigin {
    DALI_ORIGIN_EXT = 0; // DALI bus (sensors)
    DALI_ORIGIN_USR = 1; // cmd endpoint / internal processes
    DALI_ORIGIN_COMM = 2; // comm endpoint
}

enum DaliDeviceType {
    DALI_FLUORESCENT_LAMP = 0;
    DALI_EMERGENCY_LIGHTING = 1;
    DALI_DISCHARGE_LAMP = 2;
    DALI_LOW_VOLTAGE_HALOGEN_LAMP = 3;
    DALI_INCANDESCENT_LAMP = 4;
    DALI_DC_VOLTAGE = 5;
    DALI_LED_MODULE = 6;
    DALI_SWITCHING_FUNCTION = 7;
    DALI_COLOUR_CONTROL = 8;

    DALI_CONTROL_GEAR = 9;
    DALI_CONTROL_GEAR_GROUP = 10;
    DALI_CONTROL_GEAR_BROADCAST_UNADDRESSED = 11;
    DALI_CONTROL_GEAR_BROADCAST = 12;
    DALI_CONTROL_DEVICE = 13;

    DALI_MULTIPLE_DEVICE_TYPES = 0xFF;
}

enum DaliProcessStatus {
    DALI_DISCOVERY_NOT_STARTED = 0;
    DALI_DISCOVERY_RUNNING = 1;
    DALI_DISCOVERY_FINISHED = 2;
    DALI_DISCOVERY_CANCELED = 3;
    DALI_DISCOVERY_FAILED = 4;
    DALI_SET_ADDRESS_FINISHED = 5;
    DALI_SET_ADDRESS_FAILED = 6;
}

enum DiscoveryAddressOption {
    DALI_ADDRESS_NONE = 0;
    DALI_ADDRESS_UNADDRESSED = 1;
    DALI_ADDRESS_ALL = 2;
}

message BusUnitInfo {
    string gtin = 1 [(nanopb).max_length = 13];
    string hw_version = 2 [(nanopb).max_length = 7];
    string id_number = 3 [(nanopb).max_length = 20];
    string fw_version = 4 [(nanopb).max_length = 7];
    string version_101 = 5 [(nanopb).max_length = 3];
    string version_102 = 6 [(nanopb).max_length = 3];
    string version_103 = 7 [(nanopb).max_length = 3];
    string control_device_units = 8 [(nanopb).max_length = 3];
    string control_gear_units = 9 [(nanopb).max_length = 3];
    string unit_index = 10 [(nanopb).max_length = 3];
}

// PATCH coap://<ip>:<port>/dali/<net [1..4]>/cfg
message DaliCfgReq {
    BooleanSetting enabled = 1;
    BooleanSetting bus_power = 2;
    String64Setting name = 3;

    BooleanSetting override_enabled = 4;
    BooleanSetting override_cancelable = 5;

    BooleanSetting configured = 6;
    BooleanSetting local_setup_enabled = 7;
    TestStatus test_status = 8;
}

// response to GET coap://<ip>:<port>/dali/<net [1..4]>/cfg
// response to PATCH coap://<ip>:<port>/dali/<net [1..4]>/cfg
message DaliCfgResp {
    // cfg
    bool enabled = 3;
    bool bus_power = 4;
    string name = 5 [(nanopb).max_length = 64];

    bool override_enabled = 6;
    bool override_cancelable = 7;

    bool configured = 8;
    bool local_setup_enabled = 9;
    TestStatus test_status = 10;
}

// PUT coap://<ip>:<port>/dali/<net [1..4]>/comm
message DaliTxReq {
    DaliPktType type = 1;
    DaliPrio prio = 2;
    repeated uint32 pkts = 3 [(nanopb).max_count = 16];
}

message DaliRxResp {
    message DaliRxPkt {
        uint32 pkt = 1;
        DaliAnswerType answer_type = 2;
        uint32 answer = 3;
        uint32 settling_time = 4;
    }

    enum DaliRxEvent {
        DALI_RX_EVENT_PWR_GONE = 0;
        DALI_RX_EVENT_PWR_FAIL = 1;
        DALI_RX_EVENT_PWR_GOOD = 2;
        DALI_RX_EVENT_FRAME_ERR = 3;
        DALI_RX_EVENT_UNSUPPORTED_FRAME_LEN = 4;
        DALI_RX_EVENT_SHORT_ADDR_CHANGED = 5;
    }

    uint32 timestamp = 1;
    oneof content {
        DaliRxPkt pkt = 10;
        DaliRxEvent event = 11;
    }
}

// response to GET coap://<ip>:<port>/dali/<net [1..4]>/comm
message DaliRxRespSeq {
    repeated DaliRxResp resps = 1 [(nanopb).max_count = 16];
    DaliPktOrigin pkt_origin = 2;
    DaliPktType pkt_type = 3;
}

// PATCH coap://<ip>:<port>/dali/<net [1..4]>/cmd
message DaliCmd {
    message ReqGear{
        enum GearCmd {
            DISCOVER = 0;
            CANCEL_DISCOVER = 1;
            SET_SHORT_ADDRESS = 2;

            //Fluorescent Lamp
            SEND_DAPC = 3;
            SEND_GO_TO_SCENE = 4;
            SEND_OFF = 5;
            SEND_UP = 6;
            SEND_DOWN = 7;
            SEND_STEP_UP = 8;
            SEND_STEP_DOWN = 9;
            SEND_RECALL_MAX_LEVEL = 10;
            SEND_RECALL_MIN_LEVEL = 11;
            SEND_STEP_DOWN_AND_OFF = 12;
            SEND_ON_AND_STEP_UP = 13;
            SEND_GO_TO_LAST_ACTIVE_LEVEL = 14;
            SEND_IDENTIFY_DEVICE = 15;
            SEND_CONTINUOUS_UP = 16;
            SEND_CONTINUOUS_DOWN = 17;
            SEND_RESET = 18;

            GET_BUS_UNIT_INFO = 19;
            WRITE_CONFIG = 20;
            READ_CONFIG = 21;
            SET_OVERRIDE = 22;
            GET_POWER_LEVEL = 23;

            GET_ON_TIME_S = 24;
            SET_ON_TIME_S = 25;
        }

        GearCmd cmd = 1;

        oneof param {
            int32 addr = 10; // SET_SHORT_ADDRESS
            double value = 11;  // SEND_DAPC / SET OVERRIDE
            int32 scene = 12;   // SEND_GO_TO_SCENE
            DaliDeviceCfgReq cfg = 13; // WRITE_CONFIG
            DiscoveryAddressOption addr_option = 14; // DISCOVER
        }
    }

    message RespGear {
        oneof payload {
            BusUnitInfo bus_unit_info = 1; // GET_BUS_UNIT_INFO
            DaliDeviceCfgResp cfg = 2; // READ_CONFIG
            double value = 3; // GET_POWER_LEVEL / GET_ON_TIME_S
        }
    }

    message ReqCdev{
        enum CdevCmd {
            DISCOVER = 0;
            CANCEL_DISCOVER = 1;
            SET_SHORT_ADDRESS = 2;

            SEND_IDENTIFY_DEVICE = 3;
            SEND_RESET = 4;
            SEND_RESET_POWER_CYCLE_SEEN = 5;
            SEND_START_QUIESCENT_MODE = 6;
            SEND_STOP_QUIESCENT_MODE = 7;

            GET_BUS_UNIT_INFO = 8;
            WRITE_CONFIG = 9;
            READ_CONFIG = 10;
            SET_OVERRIDE = 11; // ?
            GET_SENSOR_VAL = 12;
        }

        CdevCmd cmd = 1;

        oneof param {
            int32 addr = 10; // SET_SHORT_ADDRESS
            double value = 11;  // SEND_DAPC / SET OVERRIDE
            int32 scene = 12;   // SEND_GO_TO_SCENE
            DaliDeviceCfgReq cfg = 13; // WRITE_CONFIG
            DiscoveryAddressOption addr_option = 14; // DISCOVER
        }
    }

    message RespCdev {
        oneof payload {
            BusUnitInfo bus_unit_info = 1;
            DaliDeviceCfgResp cfg = 2;
            double sensor_val = 3;
        }
    }

    enum MsgType {
        TYPE_REQ_GEAR = 0; // ReqGear
        TYPE_RESP_GEAR =1; // RespGear

        TYPE_REQ_CDEV = 2; // ReqCdev
        TYPE_RESP_CDEV = 3; // RespCdev
    }

    DaliDeviceType type = 1;
    uint32 addr = 2;

    MsgType msg_type = 3;
    oneof payload {
        ReqGear req_gear = 10;
        RespGear resp_gear = 11;
        ReqCdev req_cdev = 12;
        RespCdev resp_cdev = 13;
    }

}

message DaliDeviceCfgReq{
    // cfg
    Uint32Setting groups = 1;
}

message DaliDeviceCfgResp {
    // info
    DaliDeviceType device_type = 1;

    // cfg
    uint32 groups = 2;
}

// GET coap://<ip>:<port>/dali/<net [1..4]>/gear
message DaliGearResp {
    DaliProcessStatus status = 1;
    uint32 disc_progress = 2;

    uint64 short_addresses = 3;
    uint64 address_conflict = 4;
    uint64 error = 5;
    uint64 overridden = 6;
    uint64 identify_active = 7;
    uint64 lamp_on = 8;
}

// GET coap://<ip>:<port>/dali/<net [1..4]>/cdev
message DaliCdevResp {
    DaliProcessStatus status = 1;
    uint32 disc_progress = 2;

    uint64 short_addresses = 3;
}
