syntax = "proto3";

import "shared.proto";
import "nanopb.proto";

// GO
option go_package = "git-ima.europe.phoenixcontact.com/abacusgo/linkbusgo";

// JAVA settings
option java_multiple_files = false;
option java_package = "com.phoenixcontact.emalyticscatanio.message";
option java_outer_classname = "EmalyticsCatanIoUoi";

/* universal outputs *********************************************************/
// type selection, disable, inversion, override, cov, default

enum UoiType {
    UOI_TYPE_DONT_CHANGE = 0;
    UOI_TYPE_DEFAULT = 1;
    UOI_TYPE_DO = 2;
    UOI_TYPE_DI = 3;
    UOI_TYPE_COUNTER = 4;
    UOI_TYPE_AO_VOLTAGE = 5;
}

// write config request
// PATCH coap://<ip>:<port>/uoi/<channel>/cfg
message UoiCfgReq{
    // general
    BooleanSetting enabled = 1;
    UoiType type = 2; // UOI
    String64Setting name = 3;
    BooleanSetting override_enabled = 4;
    BooleanSetting override_cancelable = 5;

    // default value
    BooleanSetting digital_default_val = 6; // DO
    FloatSetting analog_default_val = 7; // AO
    BooleanSetting use_default_val_on_start = 8; // AO / DO //false: DONT_CHANGE
    BooleanSetting use_default_val_on_failure = 9; // AO / DO //false: DONT_CHANGE

    // signal
    BooleanSetting inverted = 10; // DI / DO
    LineSetting two_point_calibration = 11; // AO
    CurveSetting characteristic_curve = 12; // AO
    String16Setting unit = 13; // AO / DI
    FloatSetting counter_scale = 14; // DI

    // cov
    FloatSetting cov_increment = 15; // AO / DI
    Uint32Setting min_send_time_ms = 16; // DI
    Uint32Setting max_send_time_ms = 17; // DI

    // limits
    FloatSetting minimum = 18; // AO
    FloatSetting maximum = 19; // AO
    FloatSetting lower_fault_level = 20; // AO
    FloatSetting upper_fault_level = 21; // AO

    BooleanSetting debounced = 22; // DI

    String16Setting false_text = 23; // DI / DO
    String16Setting true_text = 24; // DI / DO

    BooleanSetting configured = 25;
    BooleanSetting local_setup_enabled = 26;
    TestStatus test_status = 27;
}

// read and write config response
// response to GET coap://<ip>:<port>/uoi/<channel>/cfg
// response to PATCH coap://<ip>:<port>/uoi/<channel>/cfg
message UoiCfgResp{
    // general
    bool enabled = 1;
    UoiType type = 2; // UOI
    string name = 3 [(nanopb).max_length = 64];
    bool override_enabled = 4;
    bool override_cancelable = 5;

    // default value
    bool digital_default_val = 6; // DO
    float analog_default_val = 7; // AO
    bool use_default_val_on_start = 8; // AO / DO //false: DONT_CHANGE
    bool use_default_val_on_failure = 9; // AO / DO //false: DONT_CHANGE

    // signal
    bool inverted = 10; // DI / DO
    Line two_point_calibration = 11; // AO
    Curve characteristic_curve = 12; // AO
    string unit = 13 [(nanopb).max_length = 16]; // AO / DI
    float counter_scale = 14; // DI

    // cov
    float cov_increment = 15; // AO / DI
    uint32 min_send_time_ms = 16; // DI
    uint32 max_send_time_ms = 17; // DI

    // limits
    float minimum = 18; // AO
    float maximum = 19; // AO
    float lower_fault_level = 20; // AO
    float upper_fault_level = 21; // AO

    bool debounced = 22; // DI

    string false_text = 23 [(nanopb).max_length = 16]; // DI / DO
    string true_text = 24 [(nanopb).max_length = 16]; // DI / DO

    bool configured = 25;
    bool local_setup_enabled = 26;
    TestStatus test_status = 27;
}

// UOI request
// PATCH coap://<ip>:<port>/uoi/<channel>
message UoiReq{
    // set value
    BooleanSetting digital_set_val = 1; // DO
    FloatSetting analog_set_val = 2; // AO

    // init value
    Uint64Setting counter_init_val = 3; // DI / DO
    Uint32Setting init_on_time_s = 4; // DI / DO

    // override
    OverrideAction override_action = 5;
    uint32 override_duration_ms = 6;
    BooleanSetting digital_override_val = 7; // DI / DO
    FloatSetting analog_override_val = 8; // AO
    Uint64Setting counter_override_val = 9; // DI

    // set error code - only used by virtuals
    IoErrorCodeSetting error_code = 10;
}

// response to PATCH coap://<ip>:<port>/uoi/<channel>
// response to GET coap://<ip>:<port>/uoi/<channel>
message UoiResp{
    // general
    UoiType type = 1; // UOI
    PointStatus status = 2;
    IoErrorCode error_code = 3;
    uint32 override_remaining_ms = 4;

    // actual value
    bool digital_val = 5; // DI / DO
    float analog_val = 6; // AO
    uint64 counter_val = 7; // DI / DO
    uint32 on_time_s = 8; // DI / DO

    // set value
    bool digital_set_val = 9; // DO
    float analog_set_val = 10; // AO

    // actual value
    float actuator_val = 11; // AO

    TestStatus test_status = 12;
}

// response to GET coap://<ip>:<port>/uoi
message UoiRespAll {
    repeated UoiResp vals = 1;
}
